apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: rhods
spec:
  components:
    codeflare:
      devFlags: {}
      managementState: Managed
    dashboard:
      devFlags:
        manifests:
          - contextDir: ocpai/manifests/dashboard
            sourcePath: ''
            uri: 'https://github.com/glroland/aiml/tarball/main'
      managementState: Managed
    datasciencepipelines:
      devFlags: {}
      managementState: Managed
    kserve:
      devFlags: {}
      managementState: Managed
      serving:
        ingressGateway:
          certificate:
            type: SelfSigned
        managementState: Unmanaged
        name: knative-serving
    modelmeshserving:
      devFlags: {}
      managementState: Managed
    ray:
      devFlags: {}
      managementState: Managed
    trustyai:
      devFlags: {}
      managementState: Managed
    workbenches:
      devFlags: {}
      managementState: Managed

